Issue: IZPACK-1656
Use correct parameter to prefent error wile file queue operstion: "De parameter is onjuist" or  "The parameter is incorrect"

Enqueueing moving C:\Program Files\CENSORED\CENSORED\__FQ__9356852580364207950.tmp to C:\Program Files\CENSORED\CENSORED\CENSORED.exe (0x201)

java.io.IOException: File queue operation failed due to Failed to enqueue moving C:\Program Files\CENSORED\CENSORED\__FQ__9356852580364207950.tmp to C:\Program Files\CENSORED\CENSORED\CENSORED.exe due to SetupQueueCopy returned with code 87: De parameter is onjuist.
        at com.izforge.izpack.util.os.FileQueue.execute(FileQueue.java:89)
        at com.izforge.izpack.installer.unpacker.UnpackerBase.postUnpack(UnpackerBase.java:754)
        at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:300)
        at com.izforge.izpack.installer.unpacker.UnpackerBase.run(UnpackerBase.java:241)
        at java.base/java.lang.Thread.run(Thread.java:834)